"""DESIGN.md emitter — builds the versioned, platform-aware design.md/v1 doc
from a completed taste-state walk.

Single source of schema truth = Chunk 1's schema.py (imported, never redefined).
The emitter assembles the doc, validates it against schema.validate_design_md,
and serializes the front-matter via the minimal YAML emitter, mirroring the
Sample Notes DESIGN.md shape (--- front-matter --- then a markdown body).

Pure stdlib.
"""

from __future__ import annotations

import datetime as _dt
from typing import Any

from ..engine import resolver
from ..engine.floor import FLOOR_VERSION
from ..engine.schema import SCHEMA_ID, validate_design_md
from . import yaml_min
from .prompt_pack import build_prompt_pack


def _utc_stamp() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_design_doc(
    name: str,
    state: Any,
    *,
    flatten: bool = True,
    version: str | None = None,
    catalog: Any = None,
) -> dict[str, Any]:
    """Build a design.md/v1 doc object from a TasteState.

    flatten=True  -> self-contained portable doc (no `extends:`); base holds
                     tokens shared across platforms, platforms hold the diffs.
    flatten=False -> declares `extends: calm-precision@<floor>` and stores only
                     the user overrides (tiny diff, DRY).

    `version` stamps the product's design version (defaults to a timestamp).
    `catalog` (optional) lets the prompt pack cite the picks the user made.
    """
    overrides = getattr(state, "overrides", {}) or {}
    per_platform = getattr(state, "per_platform", {}) or {}
    product_version = version or _utc_stamp()

    if flatten:
        doc = resolver.flatten(name, product_version, overrides, per_platform)
    else:
        doc = {
            "schema": SCHEMA_ID,
            "name": name,
            "version": product_version,
            "extends": FLOOR_VERSION,
            "base": overrides,                 # only the deltas vs the floor
            "platforms": {p: d for p, d in per_platform.items() if d},
        }

    # Provenance + the AI prompt pack.
    doc["generated_at"] = _utc_stamp()
    doc["generated_by"] = "ui-guidance/designer (revealed-preference walk)"
    if getattr(state, "context", None):
        doc["context"] = state.context
    doc["prompt_pack"] = build_prompt_pack(state, catalog=catalog)

    return doc


def render_design_md(doc: dict[str, Any]) -> str:
    """Render a doc object to the DESIGN.md text (front-matter + body)."""
    result = validate_design_md(doc)
    if not result.ok:
        raise ValueError("DESIGN.md failed schema validation:\n  " + "\n  ".join(result.errors))

    # Split prompt_pack out of the YAML front-matter into the markdown body so
    # the front-matter stays a clean token block (matches Sample Notes shape).
    prompt_pack = doc.get("prompt_pack", [])
    fm_doc = {k: v for k, v in doc.items() if k != "prompt_pack"}

    fm = yaml_min.dump(fm_doc)
    name = doc.get("name", "Product")
    extends = doc.get("extends")
    flat_note = (
        f"Extends `{extends}` — overrides only."
        if extends
        else "Flattened / self-contained — no external floor required."
    )

    body_lines = [
        "---",
        fm.rstrip("\n"),
        "---",
        "",
        f"# {name} — Design System",
        "",
        f"Generated by the UI Guidance designer from a revealed-preference walk. {flat_note}",
        "Tokens in the front-matter are canonical: a shared `base` layer plus per-platform",
        "(`web` / `ios` / `macos`) override layers.",
        "",
        "## AI Prompt Pack",
        "",
        "Paste these into a coding agent to implement screens in this system:",
        "",
    ]
    for line in prompt_pack:
        body_lines.append(f"- {line}")
    body_lines.append("")
    return "\n".join(body_lines)
